# 异常关键字
`throws`、 `throw`、 `try`、 `catch`、 `finally`

1. `throw`语句⽤来明确地抛出⼀个异常；
```java
	@Test
    public void test() throws IOException {
		代码
//当程序执行到这一句会主动抛出一个IOException异常，后续代码会停止执行
        throw new IOException;
		代码
    }
```

2. `throws`⽤来声明⼀个⽅法可能抛出的各种异常；
```java
	@Test
    public void test() throws IOException { //声明⼀个⽅法可能抛出IOException异常
		代码1
//当程序执行到这一句会主动抛出一个IOException异常，代码2会停止执行
        throw new IOException;
		代码2
    }
```

3. `try`⽤来指定⼀块预防所有异常的程序；
```java
	@Test
    public void test(){
	try{//{}内如果出现异常会被捕获，不会影响代码2的执行
        		代码1
//当程序执行到这一句会主动抛出一个IOException异常，后续代码会停止执行
        throw new IOException;
		
    }
				代码2

    }
```

4. `catch`⼦句紧跟在try块后⾯，⽤来指定你想要捕获的异常的类型；
```java
	@Test
    public void test(){
	try{//{}内如果出现异常会被捕获，不会影响代码2的执行
        		代码1
//当程序执行到这一句会主动抛出一个IOException异常，后续代码会停止执行
        throw new IOException;
		
    }catch(IOException e){//声明想要捕获的异常的类型
        //对异常的处理代码
    }
				代码2

    }
```

5. `finally`为确保⼀段代码不管发⽣什么异常状况都要被执⾏；
```java
	@Test
    public void test(){
	try{//{}内如果出现异常会被捕获，不会影响代码2的执行
        		代码1
//当程序执行到这一句会主动抛出一个IOException异常，后续代码会停止执行
        throw new IOException;
		
    }catch(IOException e){//声明想要捕获的异常的类型
        //对异常的处理代码
    }finally{
        代码3//这里的代码始终都会被执行
    }
				代码2

    }
```

6. `try`、`catch`、`finally`总是组合式的出现

`try` + `catch`
`try`+ `catch`+ `finally`
`try`+ `finally`
# Java异常处理的抓抛模型
## 抛：指异常出现的原因
在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个对应异常类的对象，并将此对象抛出，**一旦抛出对象以后，其后的代码就不再执行**。
出现异常的原因有两种：

1. 系统自动生成的异常对象
2. 手动的生成一个异常对象，并抛出（throw）
```java
class Student{
	
	private int id;
	
	public void regist(int id) throws Exception {
		if(id > 0){
			this.id = id;
		}else{
			//手动抛出异常对象
//			throw new RuntimeException("您输入的数据非法！");
//			throw new Exception("您输入的数据非法！");
			throw new MyException("不能输入负数");

		}
		
	}

	@Override
	public String toString() {
		return "Student [id=" + id + "]";
	}
	
	
}
```
## 抓：处理异常的方法
为了保证程序的正常运行，我们通过两种方式来处被抛出的异常。

1. 在异常产生处处理
   1. `try` + `catch`
   2. `try`+ `catch`+ `finally`
   3. `try`+ `finally`
2. 抛给上一层去处理
   1.  `throws`
### 方式一
使用`try` + `catch`的方式在异常产生处处理异常
```java
try{
 		//可能出现异常的代码
 
 }catch(异常类型1 变量名1){
 		//处理异常的方式1
 }catch(异常类型2 变量名2){
 		//处理异常的方式2
 }catch(异常类型3 变量名3){
 		//处理异常的方式3
 }
 ....
 finally{
 		//一定会执行的代码
 }
 
说明：
1. finally是可的。
2. 使用try将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，
   根据此对象的类型，去catch中进行匹配
3. 一旦try中的异常对象匹配到某一个catch时，就进入catch中进行异常的处理。
   一旦处理完成，就跳出当前的try-catch结构（在没写finally的情况。继续执行其后的代码)
4. catch中的异常类型如果没子父类关系，则谁声明在上，谁声明在下无所谓。
   catch中的异常类型如果满足子父类关系，则要求子类一定声明在父类的上面。否则，报错
5. 常用的异常对象处理的方式： 
	① String  getMessage() //输出异常信息 
	② printStackTrace() //打印堆栈信息
6. 在try结构中声明的变量，再出了try结构以后，就不能再被调用
7. try-catch-finally结构可以嵌套
```
`体会1`：**使用try-catch-finally处理编译时异常，是得程序在编译时就不再报错，但是运行时仍可能报错**。相当于我们使用try-catch-finally将一个编译时可能出现的异常，延迟到运行时出现。
`体会2`：**开发中，由于运行时异常比较常见，所以我们通常就不针对运行时异常编写try-catch-finally了。针对于编译时异常，我们说一定要考虑异常的处理。**
### finally的再说明：

1. finally是可的
2. finally中声明的是一定会被执行的代码。即使catch中又出现异常了，try中return语句，catch中return语句等情况。
3. 像数据库连接、输入输出流、网络编程Socket等资源，JVM是不能自动的回收的，我们需要自己手动的进行资源的释放。此时的资源释放，就需要声明在finally中。
### 方式二
throws + 异常类型"写在方法的声明处。指明此方法执行时，可能会抛出的异常类型。
一旦当方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象，此对象满足throws后异常类型时，就会被抛出。异常代码后续的代码，就不再执行！
#### 体会开发中应该如何选择两种处理方式？

1. 如果父类中被重写的方法没throws方式处理异常，则子类重写的方法也不能使用throws，意味着如果子类重写的方法中异常，必须使用try-catch-finally方式处理。
2. 执行的方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行的。我们建议这几个方法使用throws的方式进行处理。而执行的方法a可以考虑使用try-catch-finally方式进行处理。
# 面试题
final、finally、finalize三者的区别？

# 补充：
## 方法重写的规则之一：
子类重写的方法抛出的异常类型不大于父类被重写的方法抛出的异常类型
